---

- name: Apply Fisrt Steps to all Appliances
  hosts: all
  connection: local
  roles:
    - role: start_config
      tags: ["start"]
    - role: first_steps
      tags: ["first", "steps"]
      first_steps_fips                            : "{{enable_fips}}"
      first_steps_admin_pwd                       : "{{change_admin_password}}"
      password                                    : "{{ appl_pwd }}"
      FIPS_cfg                                    : "{{ appliance_FIPS_cfg }}"
    - role: sanity_checks
      tags: ["sanity"]
    - role: set_ldap_root_pw
      tags: ["ldap", "root", "password"]
      set_ldap_root_pw_password                   : "{{ ldap_pwd }}"
    - role: set_network_hostname
      set_network_hostname_hostname               : "{{ appliance_name }}"
    - role: add_network_ipv4_aliases
      tags: ["ipv4"]
      add_network_ipv4_label                      : "1.1"
      add_network_ipv4_maskOrPrefix               : "{{ ipv4_1_1_ip_mask }}"
      add_network_ipv4_allowManagement            : False
      add_network_ipv4_alliases                   : "{{ ipv4_1_1_ip_aliases }}"
      when: ipv4_1_1_ip_aliases is defined
    - role: add_network_ipv4
      tags: ["ipv4"]
      add_network_ipv4_label                      : "1.2"
      add_network_ipv4_address                    : "{{ ipv4_1_2_ip_address }}"
      add_network_ipv4_maskOrPrefix               : "{{ ipv4_1_2_ip_mask }}"
      add_network_ipv4_allowManagement            : False
      when: ipv4_1_2_ip_address is defined
    - role: add_network_ipv4_aliases
      tags: ["ipv4"]
      add_network_ipv4_label                      : "1.2"
      add_network_ipv4_maskOrPrefix               : "{{ ipv4_1_2_ip_mask }}"
      add_network_ipv4_allowManagement            : False
      add_network_ipv4_alliases                   : "{{ ipv4_1_2_ip_aliases }}"
      when: ipv4_1_2_ip_aliases is defined
    - role: add_network_ipv4
      tags: ["dhcp"]
      add_network_ipv4_label                      : "1.3"
      add_network_ipv4_address                    : "{{ ipv4_1_3_ip_address }}"
      add_network_ipv4_maskOrPrefix               : "{{ ipv4_1_3_ip_mask }}"
      add_network_ipv4_allowManagement            : False
      when: ipv4_1_3_ip_address is defined
    - role: add_network_ipv4_aliases
      tags: ["ipv4"]
      add_network_ipv4_label                      : "1.3"
      add_network_ipv4_maskOrPrefix               : "{{ ipv4_1_3_ip_mask }}"
      add_network_ipv4_allowManagement            : False
      add_network_ipv4_alliases                   : "{{ ipv4_1_3_ip_aliases }}"
      when: ipv4_1_3_ip_aliases is defined
    - role: set_host_records
      tags: ["host records"]
      set_host_records                            : "{{ appl_hostnames }}"
      when: appl_hostnames is defined
    - role: config_dns
      tags: ["dns"]
      config_dns_primaryServer                    : "{{dns_primaryServer}}"
      config_dns_secondaryServer                  : "{{dns_secondaryServer}}"
      config_dns_tertiaryServer                   : "{{dns_tertiaryServer}}"
      config_dns_auto                             : "{{dns_auto}}"
      config_dns_autoFromInterface                : "{{dns_autoFromInterface}}"
      config_dns_searchDomains                    : "{{dns_searchDomains}}"
      when: dns_primaryServer is defined
    - role: config_ntp
      tags: ["ntp"]
      config_ntp_ntp_servers                      : "{{ntp_servers}}"
      config_ntp_timeZone                         : "{{timeZone}}"
      when: ntp_servers is defined and timeZone is defined
    - role: activate_module
      tags: ["activate", "wga"]
      activate_module_id                          : "wga"
      activate_module_code                        : "{{ lookup('file', '{{ products_path }}{{ wga_activation_file }}') }}"
      when: wga_activation_file is defined
    - role: activate_module
      tags: ["activate", "mga"]
      activate_module_id                          : "mga"
      activate_module_code                        : "{{ lookup('file', '{{ products_path }}{{ aac_activation_file }}') }}"
      when: aac_activation_file is defined
    - role: activate_module
      tags: ["activate", "federation"]
      activate_module_id                          : "federation"
      activate_module_code                        : "{{ lookup('file', '{{ products_path }}{{ federation_activation_file }}') }}"
      when: federation_activation_file is defined

- name: Pause to ensure the LMI is fully functional
  hosts: all
  connection: local   
  tasks:
    - name: Pause to ensure the LMI is fully functional
      pause:
        seconds: 10

- name: Get LMI Last Restart Timestamp
  hosts: all
  connection: local   
  tasks:
    - name: Get LMI Last Restart Timestamp
      isam:
        appliance: "{{ inventory_hostname }}"
        username:  "{{ username }}"
        password:  "{{ password }}"
        lmi_port:  "{{ lmi_port }}"
        log:       "{{ log_level }}"
        force:     "{{ force }}"
        action: ibmsecurity.isam.base.lmi.get
      check_mode: no
      register: ret_obj
    - name: Extract LMI Restart Timestamp
      set_fact:
        old_start_time: "{{ret_obj.data[0].start_time}}"
      
- name: Install Fixpack
  hosts: all
  connection: local
  roles:
    - role: install_fixpack
      install_fixpack_file                        : "{{ products_path }}{{ isam_fixpack }}"
      when: isam_fixpack is defined

- name: Pause to ensure the LMI is fully functional
  hosts: all
  connection: local   
  tasks:
    - name: Pause to ensure the LMI is fully functional
      pause:
        seconds: 10
      when: isam_fixpack is defined

- name: Pause to ensure the LMI is fully functional
  hosts: all
  connection: local   
  tasks:
    - name: Wait for LMI to Respond
      isam:
        appliance: "{{inventory_hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        lmi_port:  "{{ lmi_port }}"
        log:       "{{ log_level }}"
        force:     "{{ force }}"
        action: ibmsecurity.isam.base.lmi.await_startup
        isamapi:
          start_time: "{{old_start_time}}"
          wait_time: 120
      retries: 10
      delay: 60
      ignore_errors: true
      when: isam_fixpack is defined


